// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/endpoint/fizzbuzz/protobuf/fizzbuzz.proto

package go_micro_service_fizzbuzz

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FizzBuzzGetRequest struct {
	Int1                 uint64   `protobuf:"varint,1,opt,name=Int1,json=int1,proto3" json:"Int1,omitempty"`
	Int2                 uint64   `protobuf:"varint,2,opt,name=Int2,json=int2,proto3" json:"Int2,omitempty"`
	Limit                uint64   `protobuf:"varint,3,opt,name=Limit,json=limit,proto3" json:"Limit,omitempty"`
	Str1                 string   `protobuf:"bytes,4,opt,name=Str1,json=str1,proto3" json:"Str1,omitempty"`
	Str2                 string   `protobuf:"bytes,5,opt,name=Str2,json=str2,proto3" json:"Str2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzGetRequest) Reset()         { *m = FizzBuzzGetRequest{} }
func (m *FizzBuzzGetRequest) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzGetRequest) ProtoMessage()    {}
func (*FizzBuzzGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bcc5cdd7e883689, []int{0}
}

func (m *FizzBuzzGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzGetRequest.Unmarshal(m, b)
}
func (m *FizzBuzzGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzGetRequest.Marshal(b, m, deterministic)
}
func (m *FizzBuzzGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzGetRequest.Merge(m, src)
}
func (m *FizzBuzzGetRequest) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzGetRequest.Size(m)
}
func (m *FizzBuzzGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzGetRequest proto.InternalMessageInfo

func (m *FizzBuzzGetRequest) GetInt1() uint64 {
	if m != nil {
		return m.Int1
	}
	return 0
}

func (m *FizzBuzzGetRequest) GetInt2() uint64 {
	if m != nil {
		return m.Int2
	}
	return 0
}

func (m *FizzBuzzGetRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FizzBuzzGetRequest) GetStr1() string {
	if m != nil {
		return m.Str1
	}
	return ""
}

func (m *FizzBuzzGetRequest) GetStr2() string {
	if m != nil {
		return m.Str2
	}
	return ""
}

type FizzBuzzGetResponse struct {
	Items                []string `protobuf:"bytes,6,rep,name=Items,json=items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzGetResponse) Reset()         { *m = FizzBuzzGetResponse{} }
func (m *FizzBuzzGetResponse) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzGetResponse) ProtoMessage()    {}
func (*FizzBuzzGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bcc5cdd7e883689, []int{1}
}

func (m *FizzBuzzGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzGetResponse.Unmarshal(m, b)
}
func (m *FizzBuzzGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzGetResponse.Marshal(b, m, deterministic)
}
func (m *FizzBuzzGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzGetResponse.Merge(m, src)
}
func (m *FizzBuzzGetResponse) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzGetResponse.Size(m)
}
func (m *FizzBuzzGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzGetResponse proto.InternalMessageInfo

func (m *FizzBuzzGetResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type FizzBuzzStatsResponse struct {
	Int1                 uint64   `protobuf:"varint,1,opt,name=Int1,json=int1,proto3" json:"Int1,omitempty"`
	Int2                 uint64   `protobuf:"varint,2,opt,name=Int2,json=int2,proto3" json:"Int2,omitempty"`
	Limit                uint64   `protobuf:"varint,3,opt,name=Limit,json=limit,proto3" json:"Limit,omitempty"`
	Str1                 string   `protobuf:"bytes,4,opt,name=Str1,json=str1,proto3" json:"Str1,omitempty"`
	Str2                 string   `protobuf:"bytes,5,opt,name=Str2,json=str2,proto3" json:"Str2,omitempty"`
	Requests             uint64   `protobuf:"varint,8,opt,name=Requests,json=requests,proto3" json:"Requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzStatsResponse) Reset()         { *m = FizzBuzzStatsResponse{} }
func (m *FizzBuzzStatsResponse) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzStatsResponse) ProtoMessage()    {}
func (*FizzBuzzStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bcc5cdd7e883689, []int{2}
}

func (m *FizzBuzzStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzStatsResponse.Unmarshal(m, b)
}
func (m *FizzBuzzStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzStatsResponse.Marshal(b, m, deterministic)
}
func (m *FizzBuzzStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzStatsResponse.Merge(m, src)
}
func (m *FizzBuzzStatsResponse) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzStatsResponse.Size(m)
}
func (m *FizzBuzzStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzStatsResponse proto.InternalMessageInfo

func (m *FizzBuzzStatsResponse) GetInt1() uint64 {
	if m != nil {
		return m.Int1
	}
	return 0
}

func (m *FizzBuzzStatsResponse) GetInt2() uint64 {
	if m != nil {
		return m.Int2
	}
	return 0
}

func (m *FizzBuzzStatsResponse) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FizzBuzzStatsResponse) GetStr1() string {
	if m != nil {
		return m.Str1
	}
	return ""
}

func (m *FizzBuzzStatsResponse) GetStr2() string {
	if m != nil {
		return m.Str2
	}
	return ""
}

func (m *FizzBuzzStatsResponse) GetRequests() uint64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func init() {
	proto.RegisterType((*FizzBuzzGetRequest)(nil), "go.micro.service.fizzbuzz.FizzBuzzGetRequest")
	proto.RegisterType((*FizzBuzzGetResponse)(nil), "go.micro.service.fizzbuzz.FizzBuzzGetResponse")
	proto.RegisterType((*FizzBuzzStatsResponse)(nil), "go.micro.service.fizzbuzz.FizzBuzzStatsResponse")
}

func init() {
	proto.RegisterFile("src/endpoint/fizzbuzz/protobuf/fizzbuzz.proto", fileDescriptor_3bcc5cdd7e883689)
}

var fileDescriptor_3bcc5cdd7e883689 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x18, 0x24, 0x6d, 0x52, 0xd2, 0x15, 0x04, 0xd7, 0x2a, 0x6b, 0xf4, 0x50, 0x72, 0x2a, 0x4a, 0x37,
	0x26, 0xde, 0x3c, 0x0a, 0x5a, 0x0a, 0x9e, 0xd2, 0x27, 0x48, 0xdb, 0x6d, 0x58, 0x68, 0x76, 0xe3,
	0xee, 0x17, 0xc1, 0x3d, 0xfa, 0x0a, 0x9e, 0x7c, 0x2e, 0x5f, 0xc1, 0xa3, 0x0f, 0x21, 0xf9, 0x95,
	0x22, 0x42, 0x4f, 0x1e, 0xbf, 0xf9, 0x26, 0x33, 0x5f, 0x66, 0x16, 0x4d, 0xb5, 0x5a, 0x05, 0x4c,
	0xac, 0x73, 0xc9, 0x05, 0x04, 0x1b, 0x6e, 0xcc, 0xb2, 0x30, 0x26, 0xc8, 0x95, 0x04, 0xb9, 0x2c,
	0x36, 0x1d, 0x42, 0x2b, 0x04, 0x9f, 0xa5, 0x92, 0x66, 0x7c, 0xa5, 0x24, 0xd5, 0x4c, 0x3d, 0xf3,
	0x15, 0xa3, 0x2d, 0xc1, 0xbb, 0x48, 0xa5, 0x4c, 0xb7, 0x2c, 0x48, 0x72, 0x1e, 0x24, 0x42, 0x48,
	0x48, 0x80, 0x4b, 0xa1, 0xeb, 0x0f, 0xbd, 0xf3, 0x66, 0xdb, 0x09, 0xb3, 0x2c, 0x87, 0x97, 0x7a,
	0xe9, 0x1b, 0x84, 0x1f, 0xb8, 0x31, 0x77, 0x85, 0x31, 0x33, 0x06, 0x31, 0x7b, 0x2a, 0x98, 0x06,
	0x8c, 0x91, 0x3d, 0x17, 0x10, 0x12, 0x6b, 0x6c, 0x4d, 0xec, 0xd8, 0xe6, 0x02, 0xc2, 0x06, 0x8b,
	0x48, 0xaf, 0xc3, 0x22, 0x3c, 0x42, 0xce, 0x23, 0xcf, 0x38, 0x90, 0x7e, 0x05, 0x3a, 0xdb, 0x72,
	0x28, 0x99, 0x0b, 0x50, 0x21, 0xb1, 0xc7, 0xd6, 0x64, 0x18, 0xdb, 0x1a, 0x54, 0xd8, 0x60, 0x11,
	0x71, 0x3a, 0x2c, 0xf2, 0xaf, 0xd0, 0xf1, 0x8e, 0xb7, 0xce, 0xa5, 0xd0, 0xac, 0x14, 0x9d, 0x03,
	0xcb, 0x34, 0x19, 0x8c, 0xfb, 0x93, 0x61, 0xec, 0xf0, 0x72, 0xf0, 0xdf, 0x2d, 0x74, 0xd2, 0xb2,
	0x17, 0x90, 0x80, 0xee, 0xf8, 0xff, 0x72, 0x2c, 0xf6, 0x90, 0xdb, 0xa4, 0xa3, 0x89, 0x5b, 0x09,
	0xb8, 0xaa, 0x99, 0xa3, 0x2f, 0x0b, 0xb9, 0xed, 0x6d, 0xd8, 0xa0, 0xfe, 0x8c, 0x01, 0x9e, 0xd2,
	0x3f, 0xfb, 0xa2, 0xbf, 0x13, 0xf7, 0xe8, 0xbe, 0xf4, 0xfa, 0xa7, 0xfd, 0xd1, 0xeb, 0xc7, 0xe7,
	0x5b, 0xef, 0xd0, 0x1f, 0x76, 0xcf, 0xe4, 0xd6, 0xba, 0xc4, 0x6b, 0xe4, 0x54, 0xd9, 0xe0, 0x53,
	0x5a, 0x97, 0x4e, 0xdb, 0xd2, 0xe9, 0x7d, 0x59, 0xba, 0x77, 0xbd, 0x87, 0xcd, 0x4e, 0xba, 0xfe,
	0x51, 0x65, 0x74, 0x80, 0x7f, 0x8c, 0x96, 0x83, 0x4a, 0xf4, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xee, 0x3f, 0x5d, 0xc1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FizzBuzzClient is the client API for FizzBuzz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FizzBuzzClient interface {
	Get(ctx context.Context, in *FizzBuzzGetRequest, opts ...grpc.CallOption) (*FizzBuzzGetResponse, error)
	Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FizzBuzzStatsResponse, error)
}

type fizzBuzzClient struct {
	cc *grpc.ClientConn
}

func NewFizzBuzzClient(cc *grpc.ClientConn) FizzBuzzClient {
	return &fizzBuzzClient{cc}
}

func (c *fizzBuzzClient) Get(ctx context.Context, in *FizzBuzzGetRequest, opts ...grpc.CallOption) (*FizzBuzzGetResponse, error) {
	out := new(FizzBuzzGetResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.fizzbuzz.FizzBuzz/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fizzBuzzClient) Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FizzBuzzStatsResponse, error) {
	out := new(FizzBuzzStatsResponse)
	err := c.cc.Invoke(ctx, "/go.micro.service.fizzbuzz.FizzBuzz/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FizzBuzzServer is the server API for FizzBuzz service.
type FizzBuzzServer interface {
	Get(context.Context, *FizzBuzzGetRequest) (*FizzBuzzGetResponse, error)
	Stats(context.Context, *empty.Empty) (*FizzBuzzStatsResponse, error)
}

// UnimplementedFizzBuzzServer can be embedded to have forward compatible implementations.
type UnimplementedFizzBuzzServer struct {
}

func (*UnimplementedFizzBuzzServer) Get(ctx context.Context, req *FizzBuzzGetRequest) (*FizzBuzzGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFizzBuzzServer) Stats(ctx context.Context, req *empty.Empty) (*FizzBuzzStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterFizzBuzzServer(s *grpc.Server, srv FizzBuzzServer) {
	s.RegisterService(&_FizzBuzz_serviceDesc, srv)
}

func _FizzBuzz_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FizzBuzzGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FizzBuzzServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.fizzbuzz.FizzBuzz/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FizzBuzzServer).Get(ctx, req.(*FizzBuzzGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FizzBuzz_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FizzBuzzServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.service.fizzbuzz.FizzBuzz/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FizzBuzzServer).Stats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FizzBuzz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.service.fizzbuzz.FizzBuzz",
	HandlerType: (*FizzBuzzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _FizzBuzz_Get_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _FizzBuzz_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/endpoint/fizzbuzz/protobuf/fizzbuzz.proto",
}
